### PR TITLE
nit(refactor): remove the unnecessary for loop

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#9438

Fixing a nit. We don't need the for loop

### CODE REVIEW

**Comment by PhanLe1010** [comment]
@mergify backport 1.7.x 1.6.x

**Comment by PhanLe1010** [comment]
@mergify backport 1.7.x

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by derekbit** [comment]
We can more categories such as `nit` and `vendor` in the Conventional Commits  rules.

**Comment by derekbit** [comment]
@mergify backport v1.7.x v1.6.x

**Pull request merged**
