### PR TITLE
fix(dockerfile): fix spdk_tgt hang and exit on arm64 platform after enabling debug mode

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#9004

#### What this PR does / why we need it:

Disable the debug mode first. The issue doesn't always happen on all arm64 platforms and needs further investigation.

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
Need to check the build failure. Why did we need fuse-devel when building SPDK tgt? If we don't use it, is it feasible to skip it while building?

**Comment by derekbit** [comment]
> Why did we need fuse-devel when building SPDK tgt? 

Default spdk_tgt needs fuse-devel. I disabled it before because we don't need it. To avoid any surprise like the debug mode on arm64 platform, I think we can retain it which doesn't have negative impacts.

**Comment by derekbit** [comment]
> Need to check the build failure. 

All passed and ready for review. cc @innobead

**Comment by derekbit** [comment]
@mergify backport v1.7.x

**Pull request merged**
