### PR TITLE
grpc: add checkConnection for process manager, instance and disk services

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#7040

### CODE REVIEW

**Review by innobead — APPROVED** [review]
In general LGTM

**Comment by innobead** [comment]
@mergify backport v1.6.x

@derekbit see if need to backport to v1.5.x

**Comment by derekbit** [comment]
@mergify backport v1.5.x

**Comment by derekbit** [comment]
@mergify backport v1.4.x

**Pull request merged**
