### PR TITLE
fix(logging): demote some Info logging to Debug

### PR DESCRIPTION
**Pull request by james-munson**
#### Which issue(s) this PR fixes:

Part of https://github.com/longhorn/longhorn/issues/6702

#### What this PR does / why we need it:

Demote some noisy Info-level logging to Debug. Routine snapshotting can flood logs with Info-level output.

### CODE REVIEW

**Review by PhanLe1010 — APPROVED** [review]
LGTM

Btw, these logs has been very useful when debugging users/customer issue in the past. It would be more difficult if we don't have them. But I guess in a prod, we still shouldn't have too many logs

**Comment by derekbit** [comment]
> LGTM
> 
> Btw, these logs has been very useful when debugging users/customer issue in the past. It would be more difficult if we don't have them. But I guess in a prod, we still shouldn't have too many logs

These log messages only print once for each operation and won't result in flooding the logs, so I suggest keeping them at the INFO level.

**Comment by derekbit** [comment]
> > LGTM
> > Btw, these logs has been very useful when debugging users/customer issue in the past. It would be more difficult if we don't have them. But I guess in a prod, we still shouldn't have too many logs
> 
> These log messages only print once for each operation and won't result in flooding the logs, so I think we should keep them at the INFO level.

WDYT? @PhanLe1010 @innobead @james-munson

**Comment by innobead** [comment]
Agreed with @derekbit @PhanLe1010 . I think we should just keep this at the original level and not make panics later for troubleshooting.

**Comment by shuo-wu** [comment]
Agreed as well. keeping these logs at INFO level definitely benefits troubleshooting.

**Comment by innobead** [comment]
Let's close this PR first as discussed. cc @james-munson

**Comment by james-munson** [comment]
These log statements were picked based on the fact that each of them appeared more than 1000 times over the course of a two-week period in one support bundle.

**Pull request closed without merging**
