### PR TITLE
Add volume size to ReplicaAdd API

### PR DESCRIPTION
**Pull request by derekbit**
1. Add volume size field to EngineReplicaAddRequest in proxy.proto
2. Add volume size to ReplicaAdd API

https://github.com/longhorn/longhorn/issues/3601

**Depends on https://github.com/longhorn/longhorn-engine/pull/740**

Signed-off-by: Derek Su <derek.su@suse.com>

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM, waiting to update and merge after the engine PR merged.

**Review by c3y1huang — APPROVED** [review]

**Comment by derekbit** [comment]
The backward compatibility issue is addressed. Please help review the PR. Thank you.

**Comment by derekbit** [comment]
Updated longhorn-engine dependency. Ready for reivew.
cc @innobead

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
