### PR TITLE
Adjust the iSCSI initiator/target timeout and the engine-to-replica timeout

### PR DESCRIPTION
**Pull request by derekbit**
https://github.com/longhorn/longhorn/issues/4491

Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)

### CODE REVIEW

**Comment by derekbit** [comment]
Will update the dependencies if https://github.com/longhorn/longhorn-engine/pull/762 is merged.

**Comment by derekbit** [comment]
The PR is not really necessary.

**Comment by innobead** [comment]
@derekbit Why not required? 

Is it because the chance is related to starting engine process call with general arguments provided by longhorn manager, so nothings required to change here but longhorn manager instead.

**Comment by derekbit** [comment]
The engine process create/upgrade still rely on the longhorn-engine binary's command line, so the update of the instance-manager is necessary for this feature.

**Comment by innobead** [comment]
Exactly, clear.

**Comment by derekbit** [comment]
BTW, alway updating the instance-manager to the latest might be a good way? Let me reopen it. WDYT?

**Comment by innobead** [comment]
Sounds good to me.

**Comment by derekbit** [comment]
Will update the dependencies if https://github.com/longhorn/longhorn-engine/pull/762 is merged

**Review by innobead — APPROVED** [review]

**Pull request merged**
