### PR TITLE
feat(bitmap): use enhanced bitmap from go-common-libs

### PR DESCRIPTION
**Pull request by james-munson**
#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/7802

#### What this PR does / why we need it:

Switch to use the enhanced bitmap utility to avoid immediate reuse and port collision.

### CODE REVIEW

**Comment by james-munson** [comment]
The big part of this PR is switch from local bitmap to an enhanced one to be added to go-common-libs in https://github.com/longhorn/go-common-libs/pull/60

Marking it as `Draft` until that one is committed and the `replace =>` in go.mod can be removed.

**Review by DamiaSan — APPROVED** [review]
Just a little remainder for us all: in this repo the packages from `go-common-libs` are imported as `lh`, meanwhile in `longhorn-spdk-engine` they are imported as `common`. For example we have `lhBitmap` and `commonBitmap` for the same package, maybe in the future we could align them.

**Review by derekbit — APPROVED** [review]

**Comment by james-munson** [comment]
@mergify backport v1.7.x

**Comment by james-munson** [comment]
I would like to see this fix backported to 1.7.2, so I have set a PR up for that.

**Pull request merged**
